### ISSUE TITLE
How to back up state?

### ISSUE THREAD

**Issue by aaronduino** [thefinn93/signald#4]
Thank you for writing this. It lets Open Whisper Systems maintain one reference interface implementation while letting developers use the language of their choice.

I plan on setting this up for myself so that I can make a personal notification chat bot.
I might end up running it on a VPS, something that I'll shut down & start up often

Is there a way I can back up the Signal encryption/authentication keys, etc, so that I can move my setup between machines without having to re-register the device with a phone number?

**Comment by aaronduino** [comment]
Thank you very much for the help. I'm excited to use this library

**Comment by thefinn93** [comment]
Great! I look forward to hearing about it. signald has a lot of rough edges right now, and I want to get more feedback from users to see what isn't clear or well documented, and which rough edges are causing pain. If you're interested, stop by IRC (`#signald` on Freenode) and ask questions, etc.
