### ISSUE TITLE
Debian package installer does not create folder  /var/lib/signald/data

### ISSUE THREAD

**Issue by ad-pro** [thefinn93/signald#9]

**Comment by ad-pro** [comment]
I got quite some problems trying to use signald as explained in the wiki, before I realized that there are no data to keep profile data: /var/lib/signald/data

i created it manually and set user:group to signald. Now it works.

**Comment by thefinn93** [comment]
Fixed! Sorry about that, thanks for reporting. Feel free to reopen you still run into issues.
